# Use docker-compose for development
web:
  image: example/my_web_app:latest
  links:
    - redis
  environment:
    DATABASE_URL: 'postgrest://production-db.example.com:12345'
redis:
  image: "redis:alpine"
